# these RBAC settings allow the mock nodes to delete the Node object via a preStop handler on shutdown
# since there is no cloud-controller-manager for the mock provider as of now, this is the simplest solution
# to cleanup the Node object on deletion of the mock shoot
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node-self-deleter
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node-self-deleter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-self-deleter
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:nodes
