image:
  repository: timebertsap/gardener-extension-provider-mock
  tag: "0.1.0"
  pullPolicy: Always

replicaCount: 1
resources: {}

labels:
  app.kubernetes.io/instance: provider-mock
  app.kubernetes.io/name: gardener-extension-provider-mock

webhookConfig:
  serverPort: 443

tls:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDZDCCAkygAwIBAgIUSthfKxhhIiK4wXfUJvt0md5TLJkwDQYJKoZIhvcNAQEL
    BQAwSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJh
    bmNpc2NvMRYwFAYDVQQDEw1Nb2NrIFByb3ZpZGVyMB4XDTIwMDEyMzE0MTkwMFoX
    DTI1MDEyMTE0MTkwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYD
    VQQHEw1TYW4gRnJhbmNpc2NvMRYwFAYDVQQDEw1Nb2NrIFByb3ZpZGVyMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAupIgDAJuONnr++Zh7VKcW4M/0KNB
    pQlffWG20ybk7M0FZ/DTs8V0FXiL2ndax/JrU6MDX2az6clSbWNtWwg6KoENj6Lv
    Jbubh8niE6ZvojiMOcr30hiC1/s/abb5Lpnagb+fFzncskLhDtos5f+iEKNWICxz
    RKJJCsfQF1dVpD1J1WB9rZp40X+1BiSHAQZQHd2oeiFOsaeoDrXoFEWUzdsJGsxA
    Gb/aN570CORQF+hVZ6QQpYUfS1rkZYbtsVqkQJtksCLks+fdu3AXccuKORJQpRL9
    PA3STbb8lVbNzcbrY4VP0DkN/lAY7OT1TX0hhFgyDEyfOcHCjSQsI8SR+QIDAQAB
    o0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU
    nZ+/1xWPblSAVljjtFhB/RxUrF0wDQYJKoZIhvcNAQELBQADggEBAHPdsD60zMF9
    xNtERZhtyMRfKCFtglo6Jj4FBeoVRqjHAEzTF5WMT7ZQ/6h0fcF7hmbbQdVGYxlv
    uwN5/CTHLkDXxJAH4yPDxhJC36W5IPE3lBn67i8/olJizztZO6qE8ej9gTdIbMuC
    MEZVCDE63GBRFwZEVy+yEghFSbCXMqJcyBcPlhVpJzbpCJfv8VHiUFbUI5da16F+
    YWJoFCywwFtXE5hUgWNRlFt6kCg6Y5SjHvJTAkq8f0YQkiywRrdlRLchvTL2UzpI
    C0FGvq4/zad8UM/tNjKXHxg4fIGZlUTkcvBy6URgdupM1dgNw+BgKjWkLYdjFgG1
    1HqY8MXwBek=
    -----END CERTIFICATE-----
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEGDCCAwCgAwIBAgIUfL8W8Jyc9YJ39ZtVYZgfs2YHbecwDQYJKoZIhvcNAQEL
    BQAwSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJh
    bmNpc2NvMRYwFAYDVQQDEw1Nb2NrIFByb3ZpZGVyMB4XDTIwMDEyMzE0MTkwMFoX
    DTIxMDEyMjE0MTkwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYD
    VQQHEw1TYW4gRnJhbmNpc2NvMRYwFAYDVQQDEw1Nb2NrIFByb3ZpZGVyMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsVuh+iITnzoAn97mGYQH3r8q1iDc
    Hie3q4Bgqg4pIB3mS2EQqY4fcCs03eg1bx8sv5KJ0bvJ190xjBUF0DL95ero/SbF
    Vv5DV3+LaaouDsNQNFdeuHBrHuqIqBvdOpnqkOxn6AkeQG8zZ4UyGwCXfpWCnWBf
    T4MQzKSvuYz4l6ckgP8QAMbg0zafAfA+4RoS1asb36zx7GDGVeGGFor5AzRvShVT
    xd7lHh4439WnuicIDLf/QdYDa5xa3Hc9jAk1ugG9/IejA/6DgoQJkzUhLBCR+37R
    VXnwyln4mDQMeZq6vi6BUQvRd5Gq2opKO9jvwJkBLMTMiOZEFSbuZJxf6QIDAQAB
    o4H1MIHyMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNV
    HRMBAf8EAjAAMB0GA1UdDgQWBBTP3C5wtil3D4cRy6qarV3+F8rglDCBnQYDVR0R
    BIGVMIGSghhkb2NrZXIuZm9yLm1hYy5sb2NhbGhvc3SCIGdhcmRlbmVyLWV4dGVu
    c2lvbi1wcm92aWRlci1tb2NrgidnYXJkZW5lci1leHRlbnNpb24tcHJvdmlkZXIt
    bW9jay5nYXJkZW6CK2dhcmRlbmVyLWV4dGVuc2lvbi1wcm92aWRlci1tb2NrLmdh
    cmRlbi5zdmMwDQYJKoZIhvcNAQELBQADggEBADRo5CSfgLAhSd+2xLYAuJ9McGsc
    SXvQDtvpJ++Uanx4/z2NFk12kaPnMyUnH53FlwL056CQiH8e3ESVv+WtJ0zefWNZ
    eGYbJ+v8LQazVxuqoMq80KvonT1blqGo9OcSg7KN0ErleAFh86XWZFrViDoK8a6x
    pm8SVx3u4KUJmIY/j1InOENhzQG5MkA4lxTDVAWwJMBpFlytpyPJEUqjRVd/fEHX
    CGAIoiFhFpDewm1Nid9ass086f5FT65aGhPIgUfiiat/LUJ7vScoP5iYEZfeBhGn
    hDRAbZUCPmGKbpGk/A6rZaDVYP5dlCGDKVv9sK0MuR6OGUYbHK1hzS7jSeA=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAsVuh+iITnzoAn97mGYQH3r8q1iDcHie3q4Bgqg4pIB3mS2EQ
    qY4fcCs03eg1bx8sv5KJ0bvJ190xjBUF0DL95ero/SbFVv5DV3+LaaouDsNQNFde
    uHBrHuqIqBvdOpnqkOxn6AkeQG8zZ4UyGwCXfpWCnWBfT4MQzKSvuYz4l6ckgP8Q
    AMbg0zafAfA+4RoS1asb36zx7GDGVeGGFor5AzRvShVTxd7lHh4439WnuicIDLf/
    QdYDa5xa3Hc9jAk1ugG9/IejA/6DgoQJkzUhLBCR+37RVXnwyln4mDQMeZq6vi6B
    UQvRd5Gq2opKO9jvwJkBLMTMiOZEFSbuZJxf6QIDAQABAoIBAHCenhEmOE2AWEss
    D/Kd2x1/SGUmAoAHemKlpzv0t/qT4dt1rE3uWFoypWRPgjaolhKjq24Jj5bJ9x9b
    bhCRgJXRf9bYGrEtzXcvH0iebpajQTerTxNRF0RPay1MXENM3xzdcPFvcM07j2mp
    s3JgAtK3f3QNcRgdQrqfzJHHSUeKJNKJHUlUVQfr+uLuulPhM0/jcgSb0+Q1TXLN
    98iXbf8FqMr4OUZ10eYx3BsfyZWikPRgjbQuw7sG22SGhmSDM7JB0yoWffd3ROWr
    IrOwrsn/UKIL65NNG5DmZxy44dvM7861ypqTEKGB0joyTXwjtQPecg16u4P2r41A
    VK+8jXECgYEAyJ0anIcDMJERHmUH9k6URWKVAJKvHAxHk/YkNIkhO23Ite1Ba66s
    H5wk/1xXgHYp7+n8qPOkBTsU+lDtB1PVRWfeh7qV7N4sMJNqDN9Z1MT9Xu575g9s
    4DuCjvEf2pdIbg3osAne+xiQcdHTCyA79vbE7WYJAMzcE/0Tf/7syE0CgYEA4lLe
    PsQJDVMmR1eAO7Yy6H3XRLHZMw3KoVrXG9U7Y/0T7d55JNu8cVdOrNHiNh6Bf5A3
    IDc/ME7jv1VKCEj8rWm1Fsx3+gNENPH3zNzH8tllbjV0d9ZD/k5ZFTI4+/LT2vJ3
    ekeKRfCOQCBzoTk+j9T463o6I1RVnBxh/OfJBA0CgYEAwhGxF7FIdagwfk3QSQc1
    SnYWnKpJ+gErEUjxN11dJ6eJnez595jPa/jalaoX/+7PnQanZC3mAyVnosu8sPT5
    gR39WSI4PR+kcg15byB2P22dikN82k8bzUPkhjFe1lC5QbX03q995TybJ3CLD91M
    BRot4VZu6TZExJVzUsQi/ZUCgYEAjjvsJmAHHFOsU9ue4Gfx+IDVn/txeA9r0BoJ
    5BkPGRi8xJozYkGiXUy0ShIha0eitOuKaXmvAYoiwWU1gJ12BvnO8AQSRpJ09B05
    UYtTMcEEaM25Y3LKCnFstNB6VYTXNdt50ORS9v9mNtDuOl2Cftwmj76h+QAQSWrg
    /hMhFqUCgYAgncINN2Gl2TA/vSNJbnz6eR3+QOsGPOJpxWTPHpYvDglNjQQr+Ick
    zZ/TEQOPGAgE6Iy7RkpCu5MGsTaeefUZ+AcHcjF4AyMADloyTkc8kFKwRdFBRtf0
    oRu1Gw/3o48GF1VgDHMUBJRveQu7NsMZtGXydspfihLAhAktYDfaEg==
    -----END RSA PRIVATE KEY-----
