apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "name" . }}
  namespace: garden
data:
  tls.crt: {{ index .Values.tls "tls.crt" | b64enc }}
  tls.key: {{ index .Values.tls "tls.key" | b64enc }}
