apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: garden
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
{{ include "labels" . | indent 6 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.webhookConfig.serverPort }}
