kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  image: kindest/node:v1.16.4
  extraPortMappings:
  - containerPort: 30443
    hostPort: 443
networking:
  podSubnet: 10.1.0.0/16
  serviceSubnet: 10.96.0.1/12
