---
apiVersion: v1
kind: Secret
metadata:
  name: mock-secret
  namespace: garden-dev
type: Opaque
data:
  serviceaccount.json: Zm9v
---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: mock-secret
  namespace: garden-dev
secretRef:
  name: mock-secret
  namespace: garden-dev
