apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: mock-shoot
  namespace: garden-dev
spec:
  purpose: testing # don't deploy shoot monitoring and logging stack
  secretBindingName: mock-secret
  cloudProfileName: mock
  region: mock-west1
  provider:
    type: mock
    infrastructureConfig:
      apiVersion: mock.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
    controlPlaneConfig:
      apiVersion: mock.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
    - name: cpu-worker
      minimum: 1
      maximum: 1
      maxSurge: 1
      maxUnavailable: 0
      machine:
        type: mock-standard-2
      volume:
        type: mock-standard
        size: 20Gi
      zones:
      - mock-west1-b
  seedName: local-seed
  kubernetes:
    version: 1.16.6
    allowPrivilegedContainers: true
  # dns does not work for now
  #  dns:
  #    domain: mock-shoot.internal
  #    providers:
  #    - type: mock
  networking:
    type: mock
    pods: 100.96.0.0/11
    services: 100.64.0.0/13
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  addons:
    nginxIngress:
      enabled: false
    kubernetesDashboard:
      enabled: false
