apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-apiserver
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/description: |
      Allows Ingress from the Shoot's Kubernetes API Server to pods labeled with 'networking.gardener.cloud/from-apiserver=allowed'
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kubernetes
          garden.sapcloud.io/role: controlplane
          role: apiserver
  podSelector:
    matchLabels:
      networking.gardener.cloud/from-apiserver: allowed
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-dind-node
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/description: |
      Allows Egress to Mock Nodes from pods labeled with 'networking.gardener.cloud/to-shoot-networks=allowed'
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: dind-node
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-shoot-networks: allowed
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-node-to-node
  namespace: {{ .Release.Namespace }}
  annotations:
    gardener.cloud/description: |
      Allows Ingress from and Egress to Mock Nodes
spec:
  ingress:
    - {}
  egress:
    - {}
  podSelector:
    matchLabels:
      app: dind-node
  policyTypes:
  - Ingress
  - Egress
